### ISSUE TITLE
The final score report

### ISSUE THREAD

**Issue by AnneZhu1020** [princeton-nlp/blindfold-textgame#1]
Hi, it's a very interesting work.
I was wondering about the final score reported in Table 1. In paper _Interactive Fiction Games: A Colossal Adventure_ and _A survey of text games for reinforcement learning informed by natural language_, the score is a little different from yours. For example, the score of DRRN model in Zork1 game reported in _A survey of text games for reinforcement learning informed by natural language_ is 32.6, while the score here is reported as 39.4. Could u please give more explanations or suggestions? Thanks a lot.

**Comment by ysymyth** [comment]
the RL score has some variance, and the DRRN code might have slight differences. Just run 3-5 RL trials per games to report the average score and the confidence interval :)
